# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-20 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1, verbose_name='累计访问次数(每名用户统计间隔：1分钟)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1, verbose_name='累计访问次数(每名用户统计间隔：24小时)'),
        ),
    ]
