# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='切换文本编辑器'),
        ),
    ]
