# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20200617_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_title',
            field=models.CharField(default='评论标题', max_length=255, verbose_name='评论目标的标题'),
            preserve_default=False,
        ),
    ]
